Fixes two stack traces if xapian is not enabled and RegexSearch is used: The errors were:
TypeError: __init__() got an unexpected keyword argument 'needle_as_entered'
TypeError: spelling_suggestion() takes exactly 0 argument (2 given)